### ISSUE TITLE
"./gradlew clean run" fails with exception due to changeset 47 and 52

### ISSUE THREAD

**Issue by rvprasad** [sdkman/sdkman-db-migrations#57]
```
[main] ERROR io.sdkman.changelogs.package$$anon$1 - URL https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz responded with text/html content-type detected
[main] INFO com.github.mongobee.Mongobee - Mongobee is releasing process lock.
Exception in thread "main" com.github.mongobee.exception.MongobeeException: Invalid url: https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz
        at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:200)
        at com.github.mongobee.Mongobee.execute(Mongobee.java:156)
        at io.sdkman.DbMigration$.delayedEndpoint$io$sdkman$DbMigration$1(DbMigration.scala:10)
        at io.sdkman.DbMigration$delayedInit$body.apply(DbMigration.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at io.sdkman.DbMigration$.main(DbMigration.scala:5)
        at io.sdkman.DbMigration.main(DbMigration.scala)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.github.mongobee.Mongobee.executeChangeSetMethod(Mongobee.java:235)
        at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:181)
        ... 12 more
Caused by: com.github.mongobee.exception.MongobeeChangeSetException: Invalid url: https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz
        at io.sdkman.changelogs.package$$anon$1.checkResourceAvailable(package.scala:45)
        at io.sdkman.changelogs.package$$anon$1.validUrl(package.scala:36)
        at io.sdkman.changelogs.package$$anon$1.validUrl(package.scala:26)
        at io.sdkman.changelogs.package$$anon$4.$anonfun$validUrl$1(package.scala:52)
        at io.sdkman.changelogs.package$$anon$4.$anonfun$validUrl$1$adapted(package.scala:52)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at io.sdkman.changelogs.package$$anon$4.validUrl(package.scala:52)
        at io.sdkman.changelogs.package$$anon$4.validUrl(package.scala:49)
        at io.sdkman.changelogs.package$ValidationOps.validate(package.scala:84)
        at io.sdkman.changelogs.JavaMigrations.migrate047(JavaMigrations.scala:107)
        ... 18 more


FAILURE: Build failed with an exception.
```

**Comment by marc0der** [comment]
This is due to Oracle removing URLs. Quite easy to fix, simply remove the offending migrations. Feel free to raise a PR for that?

**Comment by rvprasad** [comment]
I commented the offending migrations to test a PR.  Once the other PR is resolved, I will create a PR for this issue.
